### ISSUE TITLE
translations?

### ISSUE THREAD

**Issue by renarena** [msimonides/homerplayer#26]
@DonnKey, i found aesop player and i think its really great! 
BUT... i need it for nonenglish speaking users.
Is there an ability to internationalize  aesopPlayer/app/src/main/res/values/strings.xml ?
I would be glad to provide german translations.
I this it is especially important for spoken texts like: 
```
    <string name="audio_prompt_slower">Slower</string>
    <string name="audio_prompt_faster">Faster</string>
    <string name="audio_prompt_louder">Louder</string>
    <string name="audio_prompt_softer">Softer</string>
    <string name="audio_prompt_normal">Normal</string>
```

```
    <string name="audio_prompt_slower">langsamer</string>
    <string name="audio_prompt_faster">schneller</string>
    <string name="audio_prompt_louder">lauter</string>
    <string name="audio_prompt_softer">leiser</string>
    <string name="audio_prompt_normal">normal</string>
```
As i have no knowledge about android programming i dont know how to change it/compile it by myself.

**Comment by msimonides** [comment]
@DonnKey, adding a new language is just a matter of [adding a `strings.xml` file in a `values-<locale>` folder](https://developer.android.com/guide/topics/resources/localization#creating-alternatives).
But if you want to make it really easy for users to translate the app, in their browser, without fiddling with XML, you could use one of the many services for collaborative translation. I am aware of two that have a free plan for small projects but I haven't used any of them myself yet: https://crowdin.com and https://localazy.com

I didn't set this up for Homer Player because the main user only interacts with the "start" and "stop" buttons. Settings are used by the more tech-savvy user configuring the device. But I see how this is different for Aesop.

@renarena, this is github for Homer Player project upon which Aesop Player is built. They are distinct projects. I don't mind the issue being filed here and you already got in touch with the author of Aesop, so all is good. Feel free to communicate here further.
However, I will close this issue in a few days because I don't consider translations a priority for Homer at the moment.

**Comment by DonnKey** [comment]
@msimonides: I won't claim GitHub expertise to be sure, but I was unable to
find an "Issues" section for the Aesop fork, just in the main (Homer)
fork.  Thus we might be stuck with what actually happened.  You can close
the issue when you wish.

@renarena: I'm not currently able to look into those translation tools, but
if you want to experiment, I'd be willing to add translation files that
were sent to me.  As Marcin notes, there are only a few words that the
non-expert user would need translated, and as far as I know partial
translations work fine (it just falls back to the default language if there
isn't a translation).  (You've identified the most important ones, since
Start and Stop are color-coded as well.)

DonnKey

**Comment by renarena** [comment]
@DonnKey: The most important words are the 5 lines i translated in my first post. The ones spoken to the user. And maybe the word "paused" which is "pausiert" or simply "Pause"
I can change the words in xml, but i dont know how to compile an .apk from it.

**Comment by DonnKey** [comment]
It may take me a few days to get to it, but if you can provide the xml
file, I can do the rest without too much trouble. (I'm in the middle of
something messy right now.)  (Either mail or a pull request would be fine,
as long as it's in the right format: the same as the English and Polish
versions. If you want credit for it, a PR would be better.)

DonnKey

**Comment by renarena** [comment]
Created an pull request - I hope i have done it correct.
I would be glad if aesop player could be available in fdroid or from @IzziSoft also. 
See https://github.com/msimonides/homerplayer/issues/20

**Comment by DonnKey** [comment]
I don't see a PR for either Homer or Aesop.  Be sure to do it for Aesop for
this request.

It's unlikely that I'll find the time or energy to deal with the issues in
#20 for Aesop, at least without a more compelling reason than I've heard.

DonnKey

**Comment by renarena** [comment]
https://github.com/renarena/aesopPlayer/pulls

Dont know why its not showing up here.

**Comment by msimonides** [comment]
> I won't claim GitHub expertise to be sure, but I was unable to
find an "Issues" section for the Aesop fork, just in the main (Homer)
fork. 

@DonnKey, you can enable "Issues" in repository settings in github: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/disabling-issues

I see there's a pull-request for Aesop, so I'm closing this issue.

**Comment by renarena** [comment]
Maybe you can use the translation for homer too?

**Comment by DonnKey** [comment]
I see the PR now (properly set up).  Something changed to make it visible.
I'm not sure what, although it MIGHT have been enabling "Issues" (grasping
at straws, possibly).

I won't get to it immediately, but fairly soon.  I'll have to "rediscover"
the build process and update Android Studio, among other things.
Hopefully Google hasn't done anything to complicate things.

Much of the translation would apply to Homer, but there are a few instances
where the "string name" has changed, and of course there are all the
additional strings in Aesop that might want to be removed for Homer.

Donn

**Comment by DonnKey** [comment]
Sigh...
I got the version with the German translation built, and it looks fine
locally.
However, I can't put it in the store -- see this website:
https://developer.android.com/distribute/best-practices/develop/target-sdk
It fails on upload.  I have no idea how much trouble moving to API 30 will
be, since it now is November and that is required.
I updated GitHub, and put the .apk as a release if you want to do it that
way.

Donn
